/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICircles,
  ICirclesInterface,
} from "../../../sol/circles/ICircles";

const _abi = [
  {
    inputs: [],
    name: "inflationDayZero",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICircles__factory {
  static readonly abi = _abi;
  static createInterface(): ICirclesInterface {
    return new Interface(_abi) as ICirclesInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICircles {
    return new Contract(address, _abi, runner) as unknown as ICircles;
  }
}
