/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDemurrage,
  IDemurrageInterface,
} from "../../../sol/circles/IDemurrage";

const _abi = [
  {
    inputs: [],
    name: "inflationDayZero",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDemurrage__factory {
  static readonly abi = _abi;
  static createInterface(): IDemurrageInterface {
    return new Interface(_abi) as IDemurrageInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDemurrage {
    return new Contract(address, _abi, runner) as unknown as IDemurrage;
  }
}
