/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStandardTreasury,
  IStandardTreasuryInterface,
} from "../../../sol/circles/IStandardTreasury";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "group",
        type: "address",
      },
    ],
    name: "vaults",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStandardTreasury__factory {
  static readonly abi = _abi;
  static createInterface(): IStandardTreasuryInterface {
    return new Interface(_abi) as IStandardTreasuryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStandardTreasury {
    return new Contract(address, _abi, runner) as unknown as IStandardTreasury;
  }
}
