/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IHub } from "./IHub";
export type { ILiftERC20 } from "./ILiftERC20";
export type { INameRegistry } from "./INameRegistry";
