/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as coreSol from "./Core.sol";
export type { coreSol };
import type * as iNameRegistrySol from "./INameRegistry.sol";
export type { iNameRegistrySol };
export type { ICircles } from "./ICircles";
export type { IDemurrage } from "./IDemurrage";
export type { IHub } from "./IHub";
export type { IStandardTreasury } from "./IStandardTreasury";
