/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as baseGroup from "./base-group";
export type { baseGroup };
import type * as membershipConditions from "./membership-conditions";
export type { membershipConditions };
