/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICircle,
  ICircleInterface,
} from "../../../sol/interfaces/ICircle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICircle__factory {
  static readonly abi = _abi;
  static createInterface(): ICircleInterface {
    return new Interface(_abi) as ICircleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICircle {
    return new Contract(address, _abi, runner) as unknown as ICircle;
  }
}
