/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface INameRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "registerShortName"
      | "registerShortNameWithNonce"
      | "updateMetadataDigest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "registerShortName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerShortNameWithNonce",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMetadataDigest",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "registerShortName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerShortNameWithNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMetadataDigest",
    data: BytesLike
  ): Result;
}

export interface INameRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): INameRegistry;
  waitForDeployment(): Promise<this>;

  interface: INameRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  registerShortName: TypedContractMethod<[], [void], "nonpayable">;

  registerShortNameWithNonce: TypedContractMethod<
    [nonce: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateMetadataDigest: TypedContractMethod<
    [metadataDigest: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "registerShortName"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerShortNameWithNonce"
  ): TypedContractMethod<[nonce: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMetadataDigest"
  ): TypedContractMethod<[metadataDigest: BytesLike], [void], "nonpayable">;

  filters: {};
}
