/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMembershipCondition,
  IMembershipConditionInterface,
} from "../../../../circles-groups/src/membership-conditions/IMembershipCondition";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "avatar",
        type: "address",
      },
    ],
    name: "passesMembershipCondition",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMembershipCondition__factory {
  static readonly abi = _abi;
  static createInterface(): IMembershipConditionInterface {
    return new Interface(_abi) as IMembershipConditionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMembershipCondition {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMembershipCondition;
  }
}
