/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace CirclesCoreAddresses {
  export type CirclesCoreStruct = {
    hub: AddressLike;
    standardTreasury: AddressLike;
    nameRegistry: AddressLike;
    erc20Lift: AddressLike;
  };

  export type CirclesCoreStructOutput = [
    hub: string,
    standardTreasury: string,
    nameRegistry: string,
    erc20Lift: string
  ] & {
    hub: string;
    standardTreasury: string;
    nameRegistry: string;
    erc20Lift: string;
  };
}

export interface CirclesV2BetaAddressesInterface extends Interface {
  getFunction(nameOrSignature: "getCirclesCore"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCirclesCore",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getCirclesCore",
    data: BytesLike
  ): Result;
}

export interface CirclesV2BetaAddresses extends BaseContract {
  connect(runner?: ContractRunner | null): CirclesV2BetaAddresses;
  waitForDeployment(): Promise<this>;

  interface: CirclesV2BetaAddressesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCirclesCore: TypedContractMethod<
    [],
    [CirclesCoreAddresses.CirclesCoreStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCirclesCore"
  ): TypedContractMethod<
    [],
    [CirclesCoreAddresses.CirclesCoreStructOutput],
    "view"
  >;

  filters: {};
}
