/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type { Circle, CircleInterface } from "../../../sol/base/Circle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346013576089908160188239f35b5f80fdfe608060405260043610156010575f80fd5b5f3560e01c806340c10f1914602c57639dc29fac14602c575f80fd5b34604f576040366003190112604f576004356001600160a01b0381168103604f57005b5f80fdfea264697066735822122020faf94a0cfdbfa8466b2076a1e576425d734be810692f06c4a33cf7abadedaa64736f6c634300081c0033";

type CircleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CircleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Circle__factory extends ContractFactory {
  constructor(...args: CircleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Circle & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Circle__factory {
    return super.connect(runner) as Circle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CircleInterface {
    return new Interface(_abi) as CircleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Circle {
    return new Contract(address, _abi, runner) as unknown as Circle;
  }
}
